name: stack_navigation
description: This packages allows navigation with a history foreach item in the bottomnavigation bar. 
version: 0.0.5
repository: https://github.com/Babwenbiber/flutter_navigation_stacks.git


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: